# Generated by Django 2.2.5 on 2019-09-24 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_from_set', to='users.Profile')),
                ('profile_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_to_set', to='users.Profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='users.Follower', to='users.Profile'),
        ),
    ]
