# Generated by Django 2.2.5 on 2019-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followees', related_query_name='followee', to='users.Profile'),
        ),
    ]
