# Generated by Django 2.2.5 on 2019-09-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190924_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='followers', through='users.Follower', to='users.Profile'),
        ),
    ]
